apiVersion: v2
name: prometheus
description: Prometheus monitoring server with Operator CRDs
type: application
version: 1.0.0

dependencies:
  - name: kube-prometheus-stack
    version: "80.0.0"
    repository: https://prometheus-community.github.io/helm-charts
